name: ubereatsdriver
description: A new Flutter project.
publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ">=2.19.2 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  sizer: ^2.0.15
  country_picker: ^2.0.20
  font_awesome: ^5.10.1
  font_awesome_flutter: ^10.4.0
  pin_code_fields: ^8.0.1
  persistent_bottom_nav_bar_v2: ^4.2.8
  firebase_core: ^2.24.2
  firebase_auth: ^4.15.3
  page_transition: ^2.1.0
  provider: ^6.1.1
  flutter_geofire: ^2.0.3
  geolocator: ^10.1.0
  cloud_firestore: ^4.14.0
  uuid: ^4.1.0
  image_picker: ^1.0.4
  firebase_storage: ^11.6.0
  carousel_slider: ^4.2.1
  flutter_styled_toast: ^2.1.3
  google_maps_flutter: ^2.3.0
  firebase_database: ^10.4.0
  flutter_swipe_button: ^2.1.1+1
  firebase_messaging: ^14.7.10
  just_audio: ^0.9.36
  flutter_polyline_points: ^1.0.0
  intl: ^0.17.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0
  flutter_launcher_icons: ^0.13.1

flutter_launcher_icons:
  android: true
  ios: true
  image_path: "assets/images/appIcon/logo.png"
  adaptive_icon_foreground: "assets/images/appIcon/logo.png"

flutter:
  uses-material-design: true
  assets:
    - assets/images/splashScreenImage/
    - assets/sounds/
    - assets/images/ride/
    - assets/images/appIcon/logo.png

  fonts:
    - family: UberMoveMedium
      fonts:
        - asset: assets/fonts/UberMoveMedium.otf

    - family: UberMoveBold
      fonts:
        - asset: assets/fonts/UberMoveBold.otf
